// ===== PORT BOUNDARY: mirrors firmware/ui.cpp — same functions, same order; edit config.h, not this file, to change timings =====
//
// Plain script, no modules, no libraries. Two halves:
//   1. a tiny Adafruit_GFX shim (below) that draws into a 240x240 ImageData
//      with the SAME pixel semantics as the real library, classic 5x7 font
//      included, so what the browser shows is what the panel would show;
//   2. the line-for-line port of firmware/ui.cpp, starting at "ui_fmt0".
// Every tunable and every colour comes from the global FW, generated by the
// build script from firmware/config.h. Nothing is hard-coded here that exists
// there.
//
// ---------------------------------------------------------------------------
// PART 1 — Adafruit_GFX shim
// Pixel-exact port of Adafruit_GFX (classic 5x7 font path only) onto a
// CanvasRenderingContext2D, for a fixed 240x240 backing buffer.
// Ported from Adafruit-GFX-Library 1.12.6 (Adafruit_GFX.cpp / .h, glcdfont.c);
// the glyph table below is a machine copy of glcdfont.c at that tag, 1280 bytes.
// ---------------------------------------------------------------------------

// prettier-ignore
const GLCDFONT = new Uint8Array([
  0x00, 0x00, 0x00, 0x00, 0x00, 0x3E, 0x5B, 0x4F, 0x5B, 0x3E, 0x3E, 0x6B, 0x4F, 0x6B, 0x3E, 0x1C, 0x3E, 0x7C, 0x3E, 0x1C,
  0x18, 0x3C, 0x7E, 0x3C, 0x18, 0x1C, 0x57, 0x7D, 0x57, 0x1C, 0x1C, 0x5E, 0x7F, 0x5E, 0x1C, 0x00, 0x18, 0x3C, 0x18, 0x00,
  0xFF, 0xE7, 0xC3, 0xE7, 0xFF, 0x00, 0x18, 0x24, 0x18, 0x00, 0xFF, 0xE7, 0xDB, 0xE7, 0xFF, 0x30, 0x48, 0x3A, 0x06, 0x0E,
  0x26, 0x29, 0x79, 0x29, 0x26, 0x40, 0x7F, 0x05, 0x05, 0x07, 0x40, 0x7F, 0x05, 0x25, 0x3F, 0x5A, 0x3C, 0xE7, 0x3C, 0x5A,
  0x7F, 0x3E, 0x1C, 0x1C, 0x08, 0x08, 0x1C, 0x1C, 0x3E, 0x7F, 0x14, 0x22, 0x7F, 0x22, 0x14, 0x5F, 0x5F, 0x00, 0x5F, 0x5F,
  0x06, 0x09, 0x7F, 0x01, 0x7F, 0x00, 0x66, 0x89, 0x95, 0x6A, 0x60, 0x60, 0x60, 0x60, 0x60, 0x94, 0xA2, 0xFF, 0xA2, 0x94,
  0x08, 0x04, 0x7E, 0x04, 0x08, 0x10, 0x20, 0x7E, 0x20, 0x10, 0x08, 0x08, 0x2A, 0x1C, 0x08, 0x08, 0x1C, 0x2A, 0x08, 0x08,
  0x1E, 0x10, 0x10, 0x10, 0x10, 0x0C, 0x1E, 0x0C, 0x1E, 0x0C, 0x30, 0x38, 0x3E, 0x38, 0x30, 0x06, 0x0E, 0x3E, 0x0E, 0x06,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x5F, 0x00, 0x00, 0x00, 0x07, 0x00, 0x07, 0x00, 0x14, 0x7F, 0x14, 0x7F, 0x14,
  0x24, 0x2A, 0x7F, 0x2A, 0x12, 0x23, 0x13, 0x08, 0x64, 0x62, 0x36, 0x49, 0x56, 0x20, 0x50, 0x00, 0x08, 0x07, 0x03, 0x00,
  0x00, 0x1C, 0x22, 0x41, 0x00, 0x00, 0x41, 0x22, 0x1C, 0x00, 0x2A, 0x1C, 0x7F, 0x1C, 0x2A, 0x08, 0x08, 0x3E, 0x08, 0x08,
  0x00, 0x80, 0x70, 0x30, 0x00, 0x08, 0x08, 0x08, 0x08, 0x08, 0x00, 0x00, 0x60, 0x60, 0x00, 0x20, 0x10, 0x08, 0x04, 0x02,
  0x3E, 0x51, 0x49, 0x45, 0x3E, 0x00, 0x42, 0x7F, 0x40, 0x00, 0x72, 0x49, 0x49, 0x49, 0x46, 0x21, 0x41, 0x49, 0x4D, 0x33,
  0x18, 0x14, 0x12, 0x7F, 0x10, 0x27, 0x45, 0x45, 0x45, 0x39, 0x3C, 0x4A, 0x49, 0x49, 0x31, 0x41, 0x21, 0x11, 0x09, 0x07,
  0x36, 0x49, 0x49, 0x49, 0x36, 0x46, 0x49, 0x49, 0x29, 0x1E, 0x00, 0x00, 0x14, 0x00, 0x00, 0x00, 0x40, 0x34, 0x00, 0x00,
  0x00, 0x08, 0x14, 0x22, 0x41, 0x14, 0x14, 0x14, 0x14, 0x14, 0x00, 0x41, 0x22, 0x14, 0x08, 0x02, 0x01, 0x59, 0x09, 0x06,
  0x3E, 0x41, 0x5D, 0x59, 0x4E, 0x7C, 0x12, 0x11, 0x12, 0x7C, 0x7F, 0x49, 0x49, 0x49, 0x36, 0x3E, 0x41, 0x41, 0x41, 0x22,
  0x7F, 0x41, 0x41, 0x41, 0x3E, 0x7F, 0x49, 0x49, 0x49, 0x41, 0x7F, 0x09, 0x09, 0x09, 0x01, 0x3E, 0x41, 0x41, 0x51, 0x73,
  0x7F, 0x08, 0x08, 0x08, 0x7F, 0x00, 0x41, 0x7F, 0x41, 0x00, 0x20, 0x40, 0x41, 0x3F, 0x01, 0x7F, 0x08, 0x14, 0x22, 0x41,
  0x7F, 0x40, 0x40, 0x40, 0x40, 0x7F, 0x02, 0x1C, 0x02, 0x7F, 0x7F, 0x04, 0x08, 0x10, 0x7F, 0x3E, 0x41, 0x41, 0x41, 0x3E,
  0x7F, 0x09, 0x09, 0x09, 0x06, 0x3E, 0x41, 0x51, 0x21, 0x5E, 0x7F, 0x09, 0x19, 0x29, 0x46, 0x26, 0x49, 0x49, 0x49, 0x32,
  0x03, 0x01, 0x7F, 0x01, 0x03, 0x3F, 0x40, 0x40, 0x40, 0x3F, 0x1F, 0x20, 0x40, 0x20, 0x1F, 0x3F, 0x40, 0x38, 0x40, 0x3F,
  0x63, 0x14, 0x08, 0x14, 0x63, 0x03, 0x04, 0x78, 0x04, 0x03, 0x61, 0x59, 0x49, 0x4D, 0x43, 0x00, 0x7F, 0x41, 0x41, 0x41,
  0x02, 0x04, 0x08, 0x10, 0x20, 0x00, 0x41, 0x41, 0x41, 0x7F, 0x04, 0x02, 0x01, 0x02, 0x04, 0x40, 0x40, 0x40, 0x40, 0x40,
  0x00, 0x03, 0x07, 0x08, 0x00, 0x20, 0x54, 0x54, 0x78, 0x40, 0x7F, 0x28, 0x44, 0x44, 0x38, 0x38, 0x44, 0x44, 0x44, 0x28,
  0x38, 0x44, 0x44, 0x28, 0x7F, 0x38, 0x54, 0x54, 0x54, 0x18, 0x00, 0x08, 0x7E, 0x09, 0x02, 0x18, 0xA4, 0xA4, 0x9C, 0x78,
  0x7F, 0x08, 0x04, 0x04, 0x78, 0x00, 0x44, 0x7D, 0x40, 0x00, 0x20, 0x40, 0x40, 0x3D, 0x00, 0x7F, 0x10, 0x28, 0x44, 0x00,
  0x00, 0x41, 0x7F, 0x40, 0x00, 0x7C, 0x04, 0x78, 0x04, 0x78, 0x7C, 0x08, 0x04, 0x04, 0x78, 0x38, 0x44, 0x44, 0x44, 0x38,
  0xFC, 0x18, 0x24, 0x24, 0x18, 0x18, 0x24, 0x24, 0x18, 0xFC, 0x7C, 0x08, 0x04, 0x04, 0x08, 0x48, 0x54, 0x54, 0x54, 0x24,
  0x04, 0x04, 0x3F, 0x44, 0x24, 0x3C, 0x40, 0x40, 0x20, 0x7C, 0x1C, 0x20, 0x40, 0x20, 0x1C, 0x3C, 0x40, 0x30, 0x40, 0x3C,
  0x44, 0x28, 0x10, 0x28, 0x44, 0x4C, 0x90, 0x90, 0x90, 0x7C, 0x44, 0x64, 0x54, 0x4C, 0x44, 0x00, 0x08, 0x36, 0x41, 0x00,
  0x00, 0x00, 0x77, 0x00, 0x00, 0x00, 0x41, 0x36, 0x08, 0x00, 0x02, 0x01, 0x02, 0x04, 0x02, 0x3C, 0x26, 0x23, 0x26, 0x3C,
  0x1E, 0xA1, 0xA1, 0x61, 0x12, 0x3A, 0x40, 0x40, 0x20, 0x7A, 0x38, 0x54, 0x54, 0x55, 0x59, 0x21, 0x55, 0x55, 0x79, 0x41,
  0x22, 0x54, 0x54, 0x78, 0x42, 0x21, 0x55, 0x54, 0x78, 0x40, 0x20, 0x54, 0x55, 0x79, 0x40, 0x0C, 0x1E, 0x52, 0x72, 0x12,
  0x39, 0x55, 0x55, 0x55, 0x59, 0x39, 0x54, 0x54, 0x54, 0x59, 0x39, 0x55, 0x54, 0x54, 0x58, 0x00, 0x00, 0x45, 0x7C, 0x41,
  0x00, 0x02, 0x45, 0x7D, 0x42, 0x00, 0x01, 0x45, 0x7C, 0x40, 0x7D, 0x12, 0x11, 0x12, 0x7D, 0xF0, 0x28, 0x25, 0x28, 0xF0,
  0x7C, 0x54, 0x55, 0x45, 0x00, 0x20, 0x54, 0x54, 0x7C, 0x54, 0x7C, 0x0A, 0x09, 0x7F, 0x49, 0x32, 0x49, 0x49, 0x49, 0x32,
  0x3A, 0x44, 0x44, 0x44, 0x3A, 0x32, 0x4A, 0x48, 0x48, 0x30, 0x3A, 0x41, 0x41, 0x21, 0x7A, 0x3A, 0x42, 0x40, 0x20, 0x78,
  0x00, 0x9D, 0xA0, 0xA0, 0x7D, 0x3D, 0x42, 0x42, 0x42, 0x3D, 0x3D, 0x40, 0x40, 0x40, 0x3D, 0x3C, 0x24, 0xFF, 0x24, 0x24,
  0x48, 0x7E, 0x49, 0x43, 0x66, 0x2B, 0x2F, 0xFC, 0x2F, 0x2B, 0xFF, 0x09, 0x29, 0xF6, 0x20, 0xC0, 0x88, 0x7E, 0x09, 0x03,
  0x20, 0x54, 0x54, 0x79, 0x41, 0x00, 0x00, 0x44, 0x7D, 0x41, 0x30, 0x48, 0x48, 0x4A, 0x32, 0x38, 0x40, 0x40, 0x22, 0x7A,
  0x00, 0x7A, 0x0A, 0x0A, 0x72, 0x7D, 0x0D, 0x19, 0x31, 0x7D, 0x26, 0x29, 0x29, 0x2F, 0x28, 0x26, 0x29, 0x29, 0x29, 0x26,
  0x30, 0x48, 0x4D, 0x40, 0x20, 0x38, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x08, 0x38, 0x2F, 0x10, 0xC8, 0xAC, 0xBA,
  0x2F, 0x10, 0x28, 0x34, 0xFA, 0x00, 0x00, 0x7B, 0x00, 0x00, 0x08, 0x14, 0x2A, 0x14, 0x22, 0x22, 0x14, 0x2A, 0x14, 0x08,
  0x55, 0x00, 0x55, 0x00, 0x55, 0xAA, 0x55, 0xAA, 0x55, 0xAA, 0xFF, 0x55, 0xFF, 0x55, 0xFF, 0x00, 0x00, 0x00, 0xFF, 0x00,
  0x10, 0x10, 0x10, 0xFF, 0x00, 0x14, 0x14, 0x14, 0xFF, 0x00, 0x10, 0x10, 0xFF, 0x00, 0xFF, 0x10, 0x10, 0xF0, 0x10, 0xF0,
  0x14, 0x14, 0x14, 0xFC, 0x00, 0x14, 0x14, 0xF7, 0x00, 0xFF, 0x00, 0x00, 0xFF, 0x00, 0xFF, 0x14, 0x14, 0xF4, 0x04, 0xFC,
  0x14, 0x14, 0x17, 0x10, 0x1F, 0x10, 0x10, 0x1F, 0x10, 0x1F, 0x14, 0x14, 0x14, 0x1F, 0x00, 0x10, 0x10, 0x10, 0xF0, 0x00,
  0x00, 0x00, 0x00, 0x1F, 0x10, 0x10, 0x10, 0x10, 0x1F, 0x10, 0x10, 0x10, 0x10, 0xF0, 0x10, 0x00, 0x00, 0x00, 0xFF, 0x10,
  0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0xFF, 0x10, 0x00, 0x00, 0x00, 0xFF, 0x14, 0x00, 0x00, 0xFF, 0x00, 0xFF,
  0x00, 0x00, 0x1F, 0x10, 0x17, 0x00, 0x00, 0xFC, 0x04, 0xF4, 0x14, 0x14, 0x17, 0x10, 0x17, 0x14, 0x14, 0xF4, 0x04, 0xF4,
  0x00, 0x00, 0xFF, 0x00, 0xF7, 0x14, 0x14, 0x14, 0x14, 0x14, 0x14, 0x14, 0xF7, 0x00, 0xF7, 0x14, 0x14, 0x14, 0x17, 0x14,
  0x10, 0x10, 0x1F, 0x10, 0x1F, 0x14, 0x14, 0x14, 0xF4, 0x14, 0x10, 0x10, 0xF0, 0x10, 0xF0, 0x00, 0x00, 0x1F, 0x10, 0x1F,
  0x00, 0x00, 0x00, 0x1F, 0x14, 0x00, 0x00, 0x00, 0xFC, 0x14, 0x00, 0x00, 0xF0, 0x10, 0xF0, 0x10, 0x10, 0xFF, 0x10, 0xFF,
  0x14, 0x14, 0x14, 0xFF, 0x14, 0x10, 0x10, 0x10, 0x1F, 0x00, 0x00, 0x00, 0x00, 0xF0, 0x10, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
  0xF0, 0xF0, 0xF0, 0xF0, 0xF0, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F,
  0x38, 0x44, 0x44, 0x38, 0x44, 0xFC, 0x4A, 0x4A, 0x4A, 0x34, 0x7E, 0x02, 0x02, 0x06, 0x06, 0x02, 0x7E, 0x02, 0x7E, 0x02,
  0x63, 0x55, 0x49, 0x41, 0x63, 0x38, 0x44, 0x44, 0x3C, 0x04, 0x40, 0x7E, 0x20, 0x1E, 0x20, 0x06, 0x02, 0x7E, 0x02, 0x02,
  0x99, 0xA5, 0xE7, 0xA5, 0x99, 0x1C, 0x2A, 0x49, 0x2A, 0x1C, 0x4C, 0x72, 0x01, 0x72, 0x4C, 0x30, 0x4A, 0x4D, 0x4D, 0x30,
  0x30, 0x48, 0x78, 0x48, 0x30, 0xBC, 0x62, 0x5A, 0x46, 0x3D, 0x3E, 0x49, 0x49, 0x49, 0x00, 0x7E, 0x01, 0x01, 0x01, 0x7E,
  0x2A, 0x2A, 0x2A, 0x2A, 0x2A, 0x44, 0x44, 0x5F, 0x44, 0x44, 0x40, 0x51, 0x4A, 0x44, 0x40, 0x40, 0x44, 0x4A, 0x51, 0x40,
  0x00, 0x00, 0xFF, 0x01, 0x03, 0xE0, 0x80, 0xFF, 0x00, 0x00, 0x08, 0x08, 0x6B, 0x6B, 0x08, 0x36, 0x12, 0x36, 0x24, 0x36,
  0x06, 0x0F, 0x09, 0x0F, 0x06, 0x00, 0x00, 0x18, 0x18, 0x00, 0x00, 0x00, 0x10, 0x10, 0x00, 0x30, 0x40, 0xFF, 0x01, 0x01,
  0x00, 0x1F, 0x01, 0x01, 0x1E, 0x00, 0x19, 0x1D, 0x17, 0x12, 0x00, 0x3C, 0x3C, 0x3C, 0x3C, 0x00, 0x00, 0x00, 0x00, 0x00,
]);

class GFX {
  constructor(ctx) {
    this._ctx = ctx;
    this._img = ctx.createImageData(240, 240);
    this._data = this._img.data;
    this.cursor_x = 0;
    this.cursor_y = 0;
    this.textcolor = 0xffff;
    this.textbgcolor = 0xffff;
    this.textsize_x = 1;
    this.textsize_y = 1;
    this.wrap = true;
    this._cp437 = false;
  }

  width() { return 240; }
  height() { return 240; }

  // 565 -> 888 (standard bit-replication expansion) and blit, clipped to bounds.
  _px(x, y, color565) {
    x |= 0; y |= 0;
    if (x < 0 || x > 239 || y < 0 || y > 239) return;
    const r5 = (color565 >> 11) & 0x1f;
    const g6 = (color565 >> 5) & 0x3f;
    const b5 = color565 & 0x1f;
    const r = (r5 << 3) | (r5 >> 2);
    const g = (g6 << 2) | (g6 >> 6);
    const b = (b5 << 3) | (b5 >> 2);
    const i = (y * 240 + x) * 4;
    const d = this._data;
    d[i] = r; d[i + 1] = g; d[i + 2] = b; d[i + 3] = 255;
  }

  drawPixel(x, y, color) { this._px(x, y, color); }

  drawFastHLine(x, y, w, color) {
    for (let i = x; i < x + w; i++) this._px(i, y, color);
  }

  drawFastVLine(x, y, h, color) {
    for (let j = y; j < y + h; j++) this._px(x, j, color);
  }

  fillRect(x, y, w, h, color) {
    for (let i = x; i < x + w; i++) this.drawFastVLine(i, y, h, color);
  }

  fillScreen(color) { this.fillRect(0, 0, 240, 240, color); }

  // General Bresenham line (Adafruit_GFX::writeLine), used by drawLine's diagonal case.
  _writeLine(x0, y0, x1, y1, color) {
    const steep = Math.abs(y1 - y0) > Math.abs(x1 - x0);
    if (steep) { [x0, y0] = [y0, x0]; [x1, y1] = [y1, x1]; }
    if (x0 > x1) { [x0, x1] = [x1, x0]; [y0, y1] = [y1, y0]; }
    const dx = x1 - x0;
    const dy = Math.abs(y1 - y0);
    let err = dx >> 1;
    const ystep = y0 < y1 ? 1 : -1;
    for (; x0 <= x1; x0++) {
      if (steep) this._px(y0, x0, color); else this._px(x0, y0, color);
      err -= dy;
      if (err < 0) { y0 += ystep; err += dx; }
    }
  }

  drawLine(x0, y0, x1, y1, color) {
    if (x0 === x1) {
      if (y0 > y1) [y0, y1] = [y1, y0];
      this.drawFastVLine(x0, y0, y1 - y0 + 1, color);
    } else if (y0 === y1) {
      if (x0 > x1) [x0, x1] = [x1, x0];
      this.drawFastHLine(x0, y0, x1 - x0 + 1, color);
    } else {
      this._writeLine(x0, y0, x1, y1, color);
    }
  }

  drawCircle(x0, y0, r, color) {
    let f = 1 - r, ddF_x = 1, ddF_y = -2 * r, x = 0, y = r;
    this._px(x0, y0 + r, color);
    this._px(x0, y0 - r, color);
    this._px(x0 + r, y0, color);
    this._px(x0 - r, y0, color);
    while (x < y) {
      if (f >= 0) { y--; ddF_y += 2; f += ddF_y; }
      x++; ddF_x += 2; f += ddF_x;
      this._px(x0 + x, y0 + y, color);
      this._px(x0 - x, y0 + y, color);
      this._px(x0 + x, y0 - y, color);
      this._px(x0 - x, y0 - y, color);
      this._px(x0 + y, y0 + x, color);
      this._px(x0 - y, y0 + x, color);
      this._px(x0 + y, y0 - x, color);
      this._px(x0 - y, y0 - x, color);
    }
  }

  fillCircle(x0, y0, r, color) {
    this.drawFastVLine(x0, y0 - r, 2 * r + 1, color);
    this._fillCircleHelper(x0, y0, r, 3, 0, color);
  }

  // corners: bit1=right half, bit2=left half. delta: extra height (for round-rects; unused here).
  _fillCircleHelper(x0, y0, r, corners, delta, color) {
    let f = 1 - r, ddF_x = 1, ddF_y = -2 * r, x = 0, y = r, px = x, py = y;
    delta++;
    while (x < y) {
      if (f >= 0) { y--; ddF_y += 2; f += ddF_y; }
      x++; ddF_x += 2; f += ddF_x;
      if (x < y + 1) {
        if (corners & 1) this.drawFastVLine(x0 + x, y0 - y, 2 * y + delta, color);
        if (corners & 2) this.drawFastVLine(x0 - x, y0 - y, 2 * y + delta, color);
      }
      if (y !== py) {
        if (corners & 1) this.drawFastVLine(x0 + py, y0 - px, 2 * px + delta, color);
        if (corners & 2) this.drawFastVLine(x0 - py, y0 - px, 2 * px + delta, color);
        py = y;
      }
      px = x;
    }
  }

  fillTriangle(x0, y0, x1, y1, x2, y2, color) {
    if (y0 > y1) { [y0, y1] = [y1, y0]; [x0, x1] = [x1, x0]; }
    if (y1 > y2) { [y2, y1] = [y1, y2]; [x2, x1] = [x1, x2]; }
    if (y0 > y1) { [y0, y1] = [y1, y0]; [x0, x1] = [x1, x0]; }

    if (y0 === y2) {
      let a = x0, b = x0;
      if (x1 < a) a = x1; else if (x1 > b) b = x1;
      if (x2 < a) a = x2; else if (x2 > b) b = x2;
      this.drawFastHLine(a, y0, b - a + 1, color);
      return;
    }

    const dx01 = x1 - x0, dy01 = y1 - y0, dx02 = x2 - x0, dy02 = y2 - y0,
      dx12 = x2 - x1, dy12 = y2 - y1;
    let sa = 0, sb = 0, y, last;

    last = (y1 === y2) ? y1 : y1 - 1;
    for (y = y0; y <= last; y++) {
      let a = x0 + Math.trunc(sa / dy01);
      let b = x0 + Math.trunc(sb / dy02);
      sa += dx01; sb += dx02;
      if (a > b) [a, b] = [b, a];
      this.drawFastHLine(a, y, b - a + 1, color);
    }

    sa = dx12 * (y - y1);
    sb = dx02 * (y - y0);
    for (; y <= y2; y++) {
      let a = x1 + Math.trunc(sa / dy12);
      let b = x0 + Math.trunc(sb / dy02);
      sa += dx12; sb += dx02;
      if (a > b) [a, b] = [b, a];
      this.drawFastHLine(a, y, b - a + 1, color);
    }
  }

  // Classic 5x7 built-in font only (no gfxFont support, matching this shim's scope).
  drawChar(x, y, c, color, bg, size_x, size_y) {
    if (size_y === undefined) size_y = size_x;
    if (x >= 240 || y >= 240 || x + 6 * size_x - 1 < 0 || y + 8 * size_y - 1 < 0) return;

    let code = typeof c === 'string' ? c.charCodeAt(0) : c;
    if (!this._cp437 && code >= 176) code++; // classic charset quirk, ported as-is

    for (let i = 0; i < 5; i++) {
      let line = GLCDFONT[code * 5 + i] | 0;
      for (let j = 0; j < 8; j++, line >>= 1) {
        if (line & 1) {
          if (size_x === 1 && size_y === 1) this._px(x + i, y + j, color);
          else this.fillRect(x + i * size_x, y + j * size_y, size_x, size_y, color);
        } else if (bg !== color) {
          if (size_x === 1 && size_y === 1) this._px(x + i, y + j, bg);
          else this.fillRect(x + i * size_x, y + j * size_y, size_x, size_y, bg);
        }
      }
    }
    if (bg !== color) {
      if (size_x === 1 && size_y === 1) this.drawFastVLine(x + 5, y, 8, bg);
      else this.fillRect(x + 5 * size_x, y, size_x, 8 * size_y, bg);
    }
  }

  setCursor(x, y) { this.cursor_x = x; this.cursor_y = y; }
  setTextSize(sx, sy) {
    this.textsize_x = sx > 0 ? sx : 1;
    this.textsize_y = (sy === undefined ? sx : sy) > 0 ? (sy === undefined ? sx : sy) : 1;
  }
  setTextColor(c, bg) {
    this.textcolor = c;
    this.textbgcolor = bg === undefined ? c : bg;
  }
  setTextWrap(w) { this.wrap = w; }

  // Adafruit_GFX::write(uint8_t) for the classic font branch.
  _write(code) {
    if (code === 10) { // '\n'
      this.cursor_x = 0;
      this.cursor_y += this.textsize_y * 8;
    } else if (code !== 13) { // '\r' ignored
      if (this.wrap && this.cursor_x + this.textsize_x * 6 > 240) {
        this.cursor_x = 0;
        this.cursor_y += this.textsize_y * 8;
      }
      this.drawChar(this.cursor_x, this.cursor_y, code, this.textcolor, this.textbgcolor,
        this.textsize_x, this.textsize_y);
      this.cursor_x += this.textsize_x * 6;
    }
  }

  print(str) {
    const s = String(str);
    for (let i = 0; i < s.length; i++) this._write(s.charCodeAt(i));
  }

  flush() { this._ctx.putImageData(this._img, 0, 0); }
}

// ---------------------------------------------------------------------------
// PART 2 — line-for-line port of firmware/ui.cpp
// Same helpers, same order, same primitives. The C side formats numbers with
// integer maths on purpose so these two round identically, and rounds every
// coordinate with floor(x + 0.5), which Math.floor(x + 0.5) matches exactly.
// ---------------------------------------------------------------------------

// --- number formatting (integer maths, identical in C++) ---------------------

// One deliberate difference from ui.cpp, the same one leds.js documents: every
// field these two format (tempC, rh, vbatPct, claudeUsd) is a `float` in the C
// UiModel, so the C++ side rounds a value that has already been narrowed to
// single precision. Math.fround reproduces that narrowing. Without it
// claudeUsd = 103.45 prints "$103.5" here and "$103.4" on the panel — the
// ui_draw trace diff catches exactly that.

// v -> "23"   (round half up, non-negative values only)
function ui_fmt0(v) {
  const n = Math.floor(Math.fround(v) + 0.5);
  return String(n);
}

// v -> "22.4" (round half up, non-negative values only)
function ui_fmt1(v) {
  const tenths = Math.floor(Math.fround(v) * 10.0 + 0.5);
  return String(Math.trunc(tenths / 10)) + "." + String(tenths % 10);
}

// 640 -> "640", 812000 -> "812K", 1240000 -> "1.2M" (integer maths, identical in C++)
function ui_fmt_tok(v) {
  if (v < 1000) {
    return String(v);
  } else if (v < 999500) {   // above this the K form would round to "1000K"
    return String(Math.trunc((v + 500) / 1000)) + "K";
  } else {
    const tenths = Math.trunc((v + 50000) / 100000);
    return String(Math.trunc(tenths / 10)) + "." + String(tenths % 10) + "M";
  }
}

function ui_strlen(s) {
  return s.length;
}

// --- colour ------------------------------------------------------------------

function ui_accent(m) {
  if (m.tempC < FW.TEMP_COMFORT_LO || m.tempC > FW.TEMP_COMFORT_HI) return FW.COL_AMBER;
  if (m.rh < FW.RH_COMFORT_LO || m.rh > FW.RH_COMFORT_HI) return FW.COL_AMBER;
  return FW.COL_GREEN;
}

// --- text --------------------------------------------------------------------

// Centre a string on cx. Adafruit advances 6*size per glyph, so the inked width
// of n glyphs is n*6*size - size (the last inter-character column is not drawn).
function ui_print_centred(g, s, cx, y, size, color) {
  const w = ui_strlen(s) * 6 * size - size;
  g.setTextSize(size);
  g.setTextColor(color);
  g.setCursor(cx - Math.trunc(w / 2), y);
  g.print(s);
}

// Print at an explicit left edge and return the x just past the last glyph.
function ui_print_at(g, s, x, y, size, color) {
  g.setTextSize(size);
  g.setTextColor(color);
  g.setCursor(x, y);
  g.print(s);
  return x + ui_strlen(s) * 6 * size - size;
}

// --- the 24-tick hour ring ---------------------------------------------------

function ui_hour_ring(g, m) {
  const cur = Math.trunc(m.hour);
  const spent = (m.lux >= FW.LUX_DAY) ? FW.COL_INK : FW.COL_DIM;  // daylight: full contrast
  for (let i = 0; i < 24; i++) {
    const a = (-90.0 + 15.0 * i) * Math.PI / 180.0;
    const ca = Math.cos(a);
    const sa = Math.sin(a);
    const rIn = (i === cur) ? FW.UI_TICK_R_IN_NOW : FW.UI_TICK_R_IN;
    let col = FW.COL_FAINT;
    if (i < cur) col = spent;
    if (i === cur) col = ui_accent(m);
    const x0 = Math.floor(FW.SCREEN_CX + FW.UI_TICK_R_OUT * ca + 0.5);
    const y0 = Math.floor(FW.SCREEN_CY + FW.UI_TICK_R_OUT * sa + 0.5);
    const x1 = Math.floor(FW.SCREEN_CX + rIn * ca + 0.5);
    const y1 = Math.floor(FW.SCREEN_CY + rIn * sa + 0.5);
    g.drawLine(x0, y0, x1, y1, col);
  }
}

// --- the tiny state glyph ----------------------------------------------------

function ui_state_glyph(g, s) {
  const cx = FW.SCREEN_CX;
  const y = FW.UI_GLYPH_Y;
  if (s === SLEEP) {
    g.drawFastHLine(cx - 4, y, 9, FW.COL_FAINT);
  } else if (s === WAKE) {
    g.fillRect(cx - 3, y - 3, 7, 7, FW.COL_INK);
  } else if (s === PRESENT) {
    g.fillCircle(cx, y, 3, FW.COL_INK);
  } else if (s === NIGHT) {
    g.drawCircle(cx, y, 3, FW.COL_DIM);
  } else if (s === ATTENTION) {
    g.fillTriangle(cx, y - 4, cx + 4, y + 3, cx - 4, y + 3, FW.COL_AMBER);
  } else {  // AWAY_PENDING
    g.drawFastHLine(cx - 4, y, 9, FW.COL_DIM);
  }
}

// --- the humidity bar --------------------------------------------------------

function ui_rh_bar(g, m) {
  const x = FW.SCREEN_CX - Math.trunc(FW.UI_BAR_W / 2);
  let v = m.rh;
  if (v < 0.0) v = 0.0;
  if (v > 100.0) v = 100.0;
  const w = Math.floor(FW.UI_BAR_W * v / 100.0 + 0.5);
  const col = (m.rh < FW.RH_COMFORT_LO || m.rh > FW.RH_COMFORT_HI) ? FW.COL_AMBER : FW.COL_GREEN;
  g.fillRect(x, FW.UI_BAR_Y, FW.UI_BAR_W, FW.UI_BAR_H, FW.COL_FAINT);
  if (w > 0) g.fillRect(x, FW.UI_BAR_Y, w, FW.UI_BAR_H, col);
}

// --- the 2 px battery pip ----------------------------------------------------

function ui_batt_pip(g, m) {
  const x = FW.SCREEN_CX - Math.trunc(FW.UI_PIP_W / 2);
  let v = m.vbatPct;
  if (v < 0.0) v = 0.0;
  if (v > 100.0) v = 100.0;
  const w = Math.floor(FW.UI_PIP_W * v / 100.0 + 0.5);
  const col = (m.vbatPct < FW.VBAT_LOW_PCT) ? FW.COL_RED : FW.COL_DIM;
  g.fillRect(x, FW.UI_PIP_Y, FW.UI_PIP_W, 2, FW.COL_FAINT);
  if (w > 0) g.fillRect(x, FW.UI_PIP_Y, w, 2, col);
  // Charging: a small filled arrow to the right of the pip.
  if (m.charging) {
    const ax = x + FW.UI_PIP_W + 6;
    g.fillTriangle(ax, FW.UI_PIP_Y - 3, ax + 5, FW.UI_PIP_Y + 1, ax, FW.UI_PIP_Y + 5, FW.COL_GREEN);
  }
}

// --- the 5-hour rate-limit window bar ----------------------------------------
// Same footprint as the humidity bar. An unknown percentage (-1, which is what
// the push script sends because the window is not derivable from the local
// transcripts) draws as an outline: the slot stays, the claim does not.
function ui_claude_bar(g, pct) {
  const x = FW.SCREEN_CX - Math.trunc(FW.UI_BAR_W / 2);
  if (pct < 0) {
    g.drawFastHLine(x, FW.UI_BAR_Y, FW.UI_BAR_W, FW.COL_FAINT);
    g.drawFastHLine(x, FW.UI_BAR_Y + FW.UI_BAR_H - 1, FW.UI_BAR_W, FW.COL_FAINT);
    g.drawFastVLine(x, FW.UI_BAR_Y, FW.UI_BAR_H, FW.COL_FAINT);
    g.drawFastVLine(x + FW.UI_BAR_W - 1, FW.UI_BAR_Y, FW.UI_BAR_H, FW.COL_FAINT);
    return;
  }
  let v = pct;
  if (v > 100) v = 100;
  const w = Math.floor(FW.UI_BAR_W * v / 100.0 + 0.5);
  g.fillRect(x, FW.UI_BAR_Y, FW.UI_BAR_W, FW.UI_BAR_H, FW.COL_FAINT);
  if (w > 0) g.fillRect(x, FW.UI_BAR_Y, w, FW.UI_BAR_H, FW.COL_CLAUDE);
}

// --- the degree mark (a 2 px ring, drawn not printed) ------------------------

function ui_degree(g, x, y, col) {
  g.drawCircle(x, y, 2, col);
}

// --- pages -------------------------------------------------------------------

// Glance: the temperature, rounded, and nothing else shouting.
function ui_page_glance(g, m) {
  const buf = ui_fmt0(m.tempC);
  const n = ui_strlen(buf);
  const wNum = n * 24 - 4;            // size 4: 24 px advance, 20 px inked
  const wUnit = 6 + 2 + 12 - 2;       // degree ring + gap + one size-2 glyph
  const left = FW.SCREEN_CX - Math.trunc((wNum + 4 + wUnit) / 2);
  ui_print_at(g, buf, left, FW.UI_BIG_Y, 4, FW.COL_INK);
  const ux = left + wNum + 4;
  const acc = ui_accent(m);
  ui_degree(g, ux + 2, FW.UI_BIG_Y + 3, acc);
  ui_print_at(g, "C", ux + 8, FW.UI_BIG_Y + 2, 2, acc);
  ui_rh_bar(g, m);
  ui_batt_pip(g, m);
}

// Detail pages: a dim label, one value at size 3, and the matching indicator.
function ui_page_temp(g, m) {
  const buf = ui_fmt1(m.tempC);
  ui_print_centred(g, "TEMP", FW.SCREEN_CX, FW.UI_LABEL_Y, 1, FW.COL_DIM);
  ui_print_centred(g, buf, FW.SCREEN_CX, FW.UI_BIG_Y + 4, 3, FW.COL_INK);
  ui_print_centred(g, "DEG C", FW.SCREEN_CX, FW.UI_BAR_Y, 1, ui_accent(m));
  ui_batt_pip(g, m);
}

function ui_page_rh(g, m) {
  const buf = ui_fmt0(m.rh);
  ui_print_centred(g, "HUMIDITY", FW.SCREEN_CX, FW.UI_LABEL_Y, 1, FW.COL_DIM);
  ui_print_centred(g, buf, FW.SCREEN_CX, FW.UI_BIG_Y, 4, FW.COL_INK);
  ui_print_centred(g, "PCT RH", FW.SCREEN_CX, FW.UI_BAR_Y - 14, 1, FW.COL_DIM);
  ui_rh_bar(g, m);
  ui_batt_pip(g, m);
}

function ui_page_batt(g, m) {
  const buf = ui_fmt0(m.vbatPct);
  ui_print_centred(g, "BATTERY", FW.SCREEN_CX, FW.UI_LABEL_Y, 1, FW.COL_DIM);
  const col = (m.vbatPct < FW.VBAT_LOW_PCT) ? FW.COL_RED : FW.COL_INK;
  ui_print_centred(g, buf, FW.SCREEN_CX, FW.UI_BIG_Y, 4, col);
  ui_print_centred(g, "PCT", FW.SCREEN_CX, FW.UI_BAR_Y - 14, 1, FW.COL_DIM);
  ui_batt_pip(g, m);
}

// Claude: today's spend, the token split, and the 5-hour window. Everything on
// this page arrives by HTTP POST; when it is older than CLAUDE_STALE_MIN the
// numbers drop to the dim colour rather than disappearing — a stale number is
// still worth something, it just should not read as live.
function ui_page_claude(g, m) {
  const stale = (m.claudeAgeMin > FW.CLAUDE_STALE_MIN);
  const ink = stale ? FW.COL_DIM : FW.COL_INK;

  ui_print_centred(g, "CLAUDE", FW.SCREEN_CX, FW.UI_LABEL_Y, 1, FW.COL_DIM);

  // "$4.2" — one decimal, in the size-3 slot the temperature detail page uses.
  const buf = ui_fmt1(m.claudeUsd);
  const money = "$" + buf;
  ui_print_centred(g, money, FW.SCREEN_CX, FW.UI_BIG_Y + 4, 3, ink);

  // "IN 812K - OUT 96K". ASCII only, deliberately: a UTF-8 middot is two bytes
  // to C++'s print() and one code unit to JS's, so the two ports would diverge.
  const tin = ui_fmt_tok(m.claudeInTok);
  const tout = ui_fmt_tok(m.claudeOutTok);
  const line = "IN " + tin + " - OUT " + tout;
  ui_print_centred(g, line, FW.SCREEN_CX, FW.UI_BAR_Y - 14, 1, stale ? FW.COL_FAINT : FW.COL_DIM);

  ui_claude_bar(g, m.claudeWindowPct);
  ui_batt_pip(g, m);
}

// --- entry point -------------------------------------------------------------

function ui_draw(g, m) {
  // JS-only, no equivalent in ui.cpp: the C UiModel always carries the Claude
  // fields, a JS caller that has not wired them yet gets the "never received"
  // defaults instead of NaN on the glass.
  if (m.claudeUsd === undefined) m.claudeUsd = 0.0;
  if (m.claudeInTok === undefined) m.claudeInTok = 0;
  if (m.claudeOutTok === undefined) m.claudeOutTok = 0;
  if (m.claudeWindowPct === undefined) m.claudeWindowPct = -1;
  if (m.claudeAgeMin === undefined) m.claudeAgeMin = 65535;

  g.fillScreen(FW.COL_BG);
  ui_hour_ring(g, m);
  ui_state_glyph(g, m.state);
  if (m.page === PAGE_DETAIL_TEMP) {
    ui_page_temp(g, m);
  } else if (m.page === PAGE_DETAIL_RH) {
    ui_page_rh(g, m);
  } else if (m.page === PAGE_DETAIL_BATT) {
    ui_page_batt(g, m);
  } else if (m.page === PAGE_CLAUDE) {
    ui_page_claude(g, m);
  } else {
    ui_page_glance(g, m);
  }
}
